name: Updater
on:
  workflow_dispatch:  # Remove cron if you don't want weekly auto-runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: HugoBlox/gh-action-updater@v2  # Updated to v2
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
          branch: main